################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: false
  debug: true
################################################################
# Enable Healthcheck
################################################################
ping: {}
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
#    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    endpoint: 'tcp://dockerproxy:2375'
    network: inbound
#    swarmMode: true

################################################################
# Access Logging
################################################################
# enable Access logs
accessLog: {}
# Configuring Multiple Filters
# accessLog:
#   filters:    
#     statusCodes:
#       - "404"
#     retryAttempts: true
#     minDuration: "10ms"

################################################################
# Traefik Logging -  DEBUG, PANIC, FATAL, ERROR, WARN, and INFO (DEFAULT is ERROR)
################################################################
log:
  level: WARN

################################################################
# Prometheus Metrics
################################################################  
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  smtp:
    address: ":587"
  imap:
    address: ":993"
  ldap:
    address: ":389"

################################################################
# TLS options
################################################################
tls:
  options:
    default:
      sniStrict: true
      minVersion: VersionTLS12

################################################################
# Challenge 
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: yoda@digital-preppers.com 
      storage: /letsencrypt/acme.json
    # TLS
#      tlsChallenge: true
    # DNS
     # dnsChallenge:
     #   provider: desec
      httpChallenge:
        # used during the challenge
        entryPoint: web
